[project]
name = "mcp-demo-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "langchain-openai>=0.3.14",
    "mcp-use>=1.2.7",
    "mcp[cli]>=1.6.0",
    "pypdf2>=3.0.1",
]
